README updated with information about how to use with promises and RxJs library.
ubidots/ubidots-node pull request #1
Opened 2018-07-28 08:40 UTC by soypipesanta

README update with information about how to use with Promises and RxJs.
Changes made just in the README.

2018-07-31 00:12 UTC, soypipesanta commented
After I did the pull-request I realized that I had made the commits with my work account and not with the personal account, I apologize for that confusion.

2018-08-07 23:38 UTC, initdav requested changes
Hello @soypipesanta,

I checked your contribution and I think it's very valuable, because it's OK to have these examples in the repository and they're a great source of information whom want to use it with Promises and RxJS; but I think having them in the Readme makes it a bit lengthy to keep it simple.

What do you think about adding them as two separate files inside a new folder called examples? And that way you can refer to them via the Readme as a link to the file.

Something kinda like this:
```
.
└── examples
    ├── with-promises.js
    └── with-rxjs.js
```

Thanks for your contribution! And I hope to hear from you soon.

2018-08-09 13:46 UTC, initdav approved these changes

2018-08-09 14:06 UTC, woakas approved these changes

2018-08-09 14:06 UTC, merged

2018-08-09 14:07 UTC, woakas commented
@soypipesanta Thanks for your contribution.